BOARD ?= samr21-xpro
include ../Makefile.tests_common

FEATURES_REQUIRED = periph_i2c
FEATURES_REQUIRED = periph_spi

USEMODULE += periph_i2c
USEMODULE += periph_spi
USEMODULE += shell

include $(RIOTBASE)/Makefile.include
